export type ProofType =
  | 'none'
  | 'photo'
  | 'video'
  | 'text'
  | 'photo_optional'
  | 'video_or_text'
  | 'optional_text'

export type MissionCategory =
  | 'TAKE THE SHOT'
  | 'MIX IT UP'
  | 'CAUSE SOME CHAOS'
  | 'FOR MARCO'

export type Mission = {
  id: number
  title: string
  category: MissionCategory
  text: string
  proofType: ProofType
  points: number
  requiresMarco: boolean
  active: boolean
}

export const missions: Mission[] = [
  // 📸 TAKE THE SHOT

  {
    id: 1,
    title: 'THE ALBUM COVER',
    category: 'TAKE THE SHOT',
    text: 'Scattate una foto seria da copertina di un album insieme a Marco.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 2,
    title: 'THE PHOTO BOMB',
    category: 'TAKE THE SHOT',
    text: 'Fate una foto con Marco mentre sullo sfondo uno sconosciuto fa qualcosa di assurdo.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 3,
    title: '30',
    category: 'TAKE THE SHOT',
    text: 'Rappresentate il numero 30 senza mostrare né scrivere il numero 30.',
    proofType: 'photo',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 4,
    title: 'THE WRONG GROUP',
    category: 'TAKE THE SHOT',
    text: 'Create un trio improbabile con Marco e una persona che conoscete appena.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 5,
    title: 'FAMILY PORTRAIT',
    category: 'TAKE THE SHOT',
    text: 'Radunate almeno 4 persone di gruppi diversi intorno a Marco e scattate una serissima foto di famiglia natalizia.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 6,
    title: 'THE DEEPFAKE',
    category: 'TAKE THE SHOT',
    text: 'Scattate una foto che tra 10 anni farà chiedere a Marco: “Ma perché stavamo facendo questa cosa?”',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 7,
    title: 'THE REENACTMENT',
    category: 'TAKE THE SHOT',
    text: 'Chiedete a qualcuno che conosce bene Marco un momento iconico della sua vita e ricreatelo in una foto insieme a lui.',
    proofType: 'photo',
    points: 20,
    requiresMarco: true,
    active: true,
  },
  {
    id: 8,
    title: 'THE DOUBLE',
    category: 'TAKE THE SHOT',
    text: 'Trovate qualcuno che non conosce Marco e fategli imitare esattamente la sua posa.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 9,
    title: 'THREE GENERATIONS',
    category: 'TAKE THE SHOT',
    text: 'Scattate una foto con Marco e tre persone di età chiaramente diverse.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 10,
    title: 'THE SAGA',
    category: 'TAKE THE SHOT',
    text: 'Scattate una foto con Marco che potrebbe avere senso soltanto a una sagra.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 11,
    title: 'THE POSTER',
    category: 'TAKE THE SHOT',
    text: 'Create la locandina fotografica di un film inesistente e inventategli un titolo.',
    proofType: 'photo',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 12,
    title: 'THE CROWD',
    category: 'TAKE THE SHOT',
    text: 'Scattate una foto con Marco in cui ogni persona presente abbia un ruolo preciso nella scena.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 13,
    title: 'SURF’S UP 🌊',
    category: 'TAKE THE SHOT',
    text: 'Scattate una foto come se foste surfisti appena usciti da una sessione epica, usando quello che trovate alla festa come attrezzatura.',
    proofType: 'photo',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 14,
    title: 'THE EVIDENCE',
    category: 'TAKE THE SHOT',
    text: 'Scattate una foto che riassuma perfettamente la serata di Marco. Marco può anche non essere nella foto.',
    proofType: 'photo',
    points: 15,
    requiresMarco: false,
    active: true,
  },

  // 🫱🏼‍🫲🏽 MIX IT UP

  {
    id: 15,
    title: 'THE STRANGER',
    category: 'MIX IT UP',
    text: 'Presentate uno sconosciuto a Marco come se fosse un suo amico da 15 anni.',
    proofType: 'none',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 16,
    title: 'THE UNDERCOVER FRIEND',
    category: 'MIX IT UP',
    text: 'Uno sconosciuto e Marco devono comportarsi per 3 minuti come vecchi amici e inventare un aneddoto condiviso.',
    proofType: 'none',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 17,
    title: 'THE SECRET AGENT',
    category: 'MIX IT UP',
    text: 'Fate fare a qualcuno che conosce appena Marco una domanda insolita. Salvate domanda e risposta.',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 18,
    title: 'THE LONGEST FRIENDSHIP',
    category: 'MIX IT UP',
    text: 'Trovate qualcuno che conosce Marco da più tempo possibile e chiedetegli una cosa che Marco faceva da giovane e che non è mai cambiata.',
    proofType: 'optional_text',
    points: 10,
    requiresMarco: false,
    active: true,
  },
  {
    id: 19,
    title: 'THE COUSIN',
    category: 'MIX IT UP',
    text: 'Trovate un “cugino” sconosciuto e fategli raccontare a Marco un fatto che dovrebbe conoscere soltanto la famiglia.',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 20,
    title: 'THE WITNESS',
    category: 'MIX IT UP',
    text: 'Fatevi raccontare una storia vera e incredibile su Marco. Poi chiedetegli “È vero che…?” senza rivelare la fonte.',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 21,
    title: 'THE MATCHMAKER',
    category: 'MIX IT UP',
    text: 'Presentate due persone che non si conoscono raccontando per ciascuna un fatto vero e uno inventato.',
    proofType: 'none',
    points: 10,
    requiresMarco: false,
    active: true,
  },
  {
    id: 22,
    title: 'THE INTERVIEW',
    category: 'MIX IT UP',
    text: 'Chiedete a una persona che conosce appena Marco: “Qual è la prima cosa che ti viene in mente quando senti Marco?”',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 23,
    title: 'THE INTRODUCTION',
    category: 'MIX IT UP',
    text: 'Portate da Marco qualcuno che non conosce bene, presentateli e poi sparite.',
    proofType: 'none',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 24,
    title: 'THE WRONG ANSWER',
    category: 'MIX IT UP',
    text: 'Fate a Marco una domanda semplice di cui conoscete la risposta. Qualunque cosa dica, insistete per 30 secondi che sia sbagliata.',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 25,
    title: 'THE SIDE QUEST',
    category: 'MIX IT UP',
    text: 'Trovate uno sconosciuto e avete 60 secondi per inventare insieme una missione segreta per Marco: fattibile, leggermente assurda e qualcosa che non farebbe spontaneamente.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 26,
    title: 'THE STRANGER’S WISH',
    category: 'MIX IT UP',
    text: 'Chiedete a uno sconosciuto di lasciare un augurio a una persona che non conosce e che sta compiendo 30 anni.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },

  // 🧨 CAUSE SOME CHAOS

  {
    id: 27,
    title: 'THE SPEECH',
    category: 'CAUSE SOME CHAOS',
    text: 'Convincete almeno 3 persone a fare un brindisi spontaneo per Marco.',
    proofType: 'none',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 28,
    title: 'THE QUESTION',
    category: 'CAUSE SOME CHAOS',
    text: 'Fate a Marco una domanda completamente assurda e ottenete una risposta seria.',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 29,
    title: 'THE POSE',
    category: 'CAUSE SOME CHAOS',
    text: 'Convincete almeno 5 persone a mettersi nella stessa posa senza spiegare perché.',
    proofType: 'photo',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 30,
    title: 'THE CONFUSION',
    category: 'CAUSE SOME CHAOS',
    text: 'Fate qualcosa che porti Marco a dire spontaneamente: “Ma perché?”',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 31,
    title: 'THE FAKE TRADITION',
    category: 'CAUSE SOME CHAOS',
    text: 'Inventate una nuova tradizione per il compleanno di Marco e convincete almeno 3 persone a seguirla.',
    proofType: 'none',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 32,
    title: 'THE WRONG TOAST',
    category: 'CAUSE SOME CHAOS',
    text: 'Fate un brindisi solenne per qualcosa che non ha nulla a che vedere con il compleanno. Alla fine brindate comunque a Marco.',
    proofType: 'photo_optional',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 33,
    title: 'THE PAPARAZZI TEAM',
    category: 'CAUSE SOME CHAOS',
    text: 'Reclutate altre due persone e scattate 3 foto di Marco come se fosse una celebrità inseguita dai paparazzi. Caricate la migliore.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 34,
    title: 'THE NPC',
    category: 'CAUSE SOME CHAOS',
    text: 'Per 30 secondi rispondete a qualsiasi domanda di Marco con la stessa frase completamente scollegata. Poi tornate normali.',
    proofType: 'none',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 35,
    title: 'THE DEAL',
    category: 'CAUSE SOME CHAOS',
    text: 'Date a Marco due opzioni assurde e obbligatelo a sceglierne una senza spiegargli il motivo.',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 36,
    title: 'THE HYPE MAN',
    category: 'CAUSE SOME CHAOS',
    text: 'Per un minuto, ogni volta che qualcuno nomina Marco reagite come se avesse appena vinto qualcosa di enorme.',
    proofType: 'none',
    points: 10,
    requiresMarco: true,
    active: true,
  },
  {
    id: 37,
    title: 'THE 30-YEAR-OLD',
    category: 'CAUSE SOME CHAOS',
    text: 'Chiedete a 3 persone di descrivere Marco con una sola parola. Le tre parole devono essere diverse.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 38,
    title: 'THE PROPHECY',
    category: 'CAUSE SOME CHAOS',
    text: 'Fate predire a qualcuno che conosce appena Marco un evento stranamente specifico che gli accadrà entro 12 mesi.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 39,
    title: 'THE QUEST',
    category: 'CAUSE SOME CHAOS',
    text: 'Fate inventare a uno sconosciuto una missione che Marco dovrebbe completare prima di compiere 31 anni.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 40,
    title: 'THE FALSE MEMORY',
    category: 'CAUSE SOME CHAOS',
    text: 'Con uno sconosciuto inventate un falso ricordo condiviso e raccontatelo a Marco nel modo più convincente possibile.',
    proofType: 'text',
    points: 15,
    requiresMarco: true,
    active: true,
  },

  // ❤️ FOR MARCO

  {
    id: 41,
    title: '30 SECONDS',
    category: 'FOR MARCO',
    text: 'Registrate un video di massimo 30 secondi con un messaggio o un pensiero per Marco.',
    proofType: 'video',
    points: 20,
    requiresMarco: false,
    active: true,
  },
  {
    id: 42,
    title: 'THE PREDICTION',
    category: 'FOR MARCO',
    text: 'Completate la frase: “A 40 anni, Marco…”',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 43,
    title: 'ONE MEMORY',
    category: 'FOR MARCO',
    text: 'Scrivete in poche righe il vostro ricordo preferito con Marco.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 44,
    title: 'THE ADVICE',
    category: 'FOR MARCO',
    text: 'Scrivete un consiglio per i 30 anni di Marco. Non potete usare la frase “goditi la vita”.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 45,
    title: 'THE COMPLIMENT',
    category: 'FOR MARCO',
    text: 'Scrivete qualcosa che apprezzate sinceramente di Marco senza usare le parole “simpatico”, “bravo” o “unico”.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 46,
    title: 'THE SECRET STORY',
    category: 'FOR MARCO',
    text: 'Trovate qualcuno che conosce Marco da almeno 10 anni e fatevi raccontare una storia che Marco probabilmente non ha mai sentito raccontare così.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 47,
    title: 'IF MARCO WERE...',
    category: 'FOR MARCO',
    text: 'Completate: “Se Marco fosse ___, sarebbe ___ perché ___.”',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 48,
    title: 'THE TRAVELER ✈️',
    category: 'FOR MARCO',
    text: 'Se domani poteste mandare Marco in viaggio senza preavviso, dove lo mandereste e perché? Massimo 2 righe.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 49,
    title: 'READ THIS AT 40',
    category: 'FOR MARCO',
    text: 'Scrivete un messaggio che Marco dovrebbe rileggere a 40 anni. Non può essere un augurio per il suo quarantesimo compleanno.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 50,
    title: 'FOR THE BIRTHDAY BOY ❤️',
    category: 'FOR MARCO',
    text: 'Completate la frase: “Marco, una cosa che vorrei che sapessi a 30 anni è…”',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },

  {
    id: 51,
    title: 'THE SPEECH 🎤',
    category: 'CAUSE SOME CHAOS',
    text: 'Convincete Marco a fare un mini discorso in cui ringrazia con assoluta serietà “tutta la sagra” per essere venuta apposta per il suo trentesimo.',
    proofType: 'photo_optional',
    points: 20,
    requiresMarco: true,
    active: true,
  },
  {
    id: 52,
    title: 'THE DANCE FLOOR 🕺',
    category: 'CAUSE SOME CHAOS',
    text: 'Convincete almeno una persona che Marco non conosce a ballare con lui per qualche secondo.',
    proofType: 'photo',
    points: 20,
    requiresMarco: true,
    active: true,
  },
  {
    id: 53,
    title: 'THE CHAMPION 🏆',
    category: 'CAUSE SOME CHAOS',
    text: 'Marco ha appena vinto qualcosa di enorme. Festeggiatelo come un campione con un’esultanza totalmente sproporzionata.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 54,
    title: 'THE DIRECTOR 🎬',
    category: 'CAUSE SOME CHAOS',
    text: 'Fate dirigere a qualcuno che conosce poco Marco una scena drammatica con Marco protagonista, senza spiegargli il contesto.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 55,
    title: 'SAME ENERGY ⚡',
    category: 'TAKE THE SHOT',
    text: 'Trovate alla festa la persona che secondo voi ha la stessa energia di Marco e scattate una foto insieme.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 56,
    title: 'BREAKING NEWS 🎤',
    category: 'CAUSE SOME CHAOS',
    text: 'Trasformate un evento totalmente insignificante della serata in una notizia dell’ultimo minuto con Marco coinvolto. Video massimo 10 secondi.',
    proofType: 'video',
    points: 20,
    requiresMarco: true,
    active: true,
  },
  {
    id: 57,
    title: 'THE MUSEUM 🖼️',
    category: 'TAKE THE SHOT',
    text: 'Trasformate Marco in un’opera d’arte: scegliete una posa, inventate il titolo dell’opera e scattate una foto.',
    proofType: 'photo',
    points: 15,
    requiresMarco: true,
    active: true,
  },
  {
    id: 58,
    title: 'THE BEFORE & AFTER',
    category: 'TAKE THE SHOT',
    text: 'Create due versioni fotografiche: “Marco a 20 anni” e “Marco a 30 anni”.',
    proofType: 'photo',
    points: 20,
    requiresMarco: true,
    active: true,
  },
  {
    id: 59,
    title: 'THE BIRTHDAY REVIEW ⭐',
    category: 'FOR MARCO',
    text: 'Recensite Marco come se fosse un prodotto: da 1 a 5 stelle, un pregio e un difetto.',
    proofType: 'text',
    points: 15,
    requiresMarco: false,
    active: true,
  },
  {
    id: 60,
    title: 'ONE SECOND FROM TONIGHT ❤️',
    category: 'FOR MARCO',
    text: 'Scattate una foto di un momento della serata che secondo voi Marco dovrebbe conservare. Marco non deve necessariamente esserci.',
    proofType: 'photo',
    points: 20,
    requiresMarco: false,
    active: true,
  },
]

export const activeMissions = missions.filter(
  (mission) => mission.active
)