-- Allinea le missioni a app/datas/missions.ts (generato da: npm run db:missions)

insert into public.missions (id, title, category, text, proof_type, points, requires_marco, active) values
  (1, 'THE ALBUM COVER', 'TAKE THE SHOT', 'Scattate una foto seria da copertina di un album insieme a Marco.', 'photo', 15, true, true),
  (2, 'THE PHOTO BOMB', 'TAKE THE SHOT', 'Fate una foto con Marco mentre sullo sfondo uno sconosciuto fa qualcosa di assurdo.', 'photo', 15, true, true),
  (3, '30', 'TAKE THE SHOT', 'Rappresentate il numero 30 senza mostrare né scrivere il numero 30.', 'photo', 15, false, true),
  (4, 'THE WRONG GROUP', 'TAKE THE SHOT', 'Create un trio improbabile con Marco e una persona che conoscete appena.', 'photo', 15, true, true),
  (5, 'FAMILY PORTRAIT', 'TAKE THE SHOT', 'Radunate almeno 4 persone di gruppi diversi intorno a Marco e scattate una serissima foto di famiglia natalizia.', 'photo', 15, true, true),
  (6, 'THE DEEPFAKE', 'TAKE THE SHOT', 'Scattate una foto che tra 10 anni farà chiedere a Marco: “Ma perché stavamo facendo questa cosa?”', 'photo', 15, true, true),
  (7, 'THE REENACTMENT', 'TAKE THE SHOT', 'Chiedete a qualcuno che conosce bene Marco un momento iconico della sua vita e ricreatelo in una foto insieme a lui.', 'photo', 20, true, true),
  (8, 'THE DOUBLE', 'TAKE THE SHOT', 'Trovate qualcuno che non conosce Marco e fategli imitare esattamente la sua posa.', 'photo', 15, true, true),
  (9, 'THREE GENERATIONS', 'TAKE THE SHOT', 'Scattate una foto con Marco e tre persone di età chiaramente diverse.', 'photo', 15, true, true),
  (10, 'THE SAGA', 'TAKE THE SHOT', 'Scattate una foto con Marco che potrebbe avere senso soltanto a una sagra.', 'photo', 15, true, true),
  (11, 'THE POSTER', 'TAKE THE SHOT', 'Create la locandina fotografica di un film inesistente e inventategli un titolo.', 'photo', 15, false, true),
  (12, 'THE CROWD', 'TAKE THE SHOT', 'Scattate una foto con Marco in cui ogni persona presente abbia un ruolo preciso nella scena.', 'photo', 15, true, true),
  (13, 'SURF’S UP 🌊', 'TAKE THE SHOT', 'Scattate una foto come se foste surfisti appena usciti da una sessione epica, usando quello che trovate alla festa come attrezzatura.', 'photo', 15, false, true),
  (14, 'THE EVIDENCE', 'TAKE THE SHOT', 'Scattate una foto che riassuma perfettamente la serata di Marco. Marco può anche non essere nella foto.', 'photo', 15, false, true),
  (15, 'THE STRANGER', 'MIX IT UP', 'Presentate uno sconosciuto a Marco come se fosse un suo amico da 15 anni.', 'none', 10, true, true),
  (16, 'THE UNDERCOVER FRIEND', 'MIX IT UP', 'Uno sconosciuto e Marco devono comportarsi per 3 minuti come vecchi amici e inventare un aneddoto condiviso.', 'none', 10, true, true),
  (17, 'THE SECRET AGENT', 'MIX IT UP', 'Fate fare a qualcuno che conosce appena Marco una domanda insolita. Salvate domanda e risposta.', 'text', 15, true, true),
  (18, 'THE LONGEST FRIENDSHIP', 'MIX IT UP', 'Trovate qualcuno che conosce Marco da più tempo possibile e chiedetegli una cosa che Marco faceva da giovane e che non è mai cambiata.', 'optional_text', 10, false, true),
  (19, 'THE COUSIN', 'MIX IT UP', 'Trovate un “cugino” sconosciuto e fategli raccontare a Marco un fatto che dovrebbe conoscere soltanto la famiglia.', 'text', 15, true, true),
  (20, 'THE WITNESS', 'MIX IT UP', 'Fatevi raccontare una storia vera e incredibile su Marco. Poi chiedetegli “È vero che…?” senza rivelare la fonte.', 'text', 15, true, true),
  (21, 'THE MATCHMAKER', 'MIX IT UP', 'Presentate due persone che non si conoscono raccontando per ciascuna un fatto vero e uno inventato.', 'none', 10, false, true),
  (22, 'THE INTERVIEW', 'MIX IT UP', 'Chiedete a una persona che conosce appena Marco: “Qual è la prima cosa che ti viene in mente quando senti Marco?”', 'text', 15, false, true),
  (23, 'THE INTRODUCTION', 'MIX IT UP', 'Portate da Marco qualcuno che non conosce bene, presentateli e poi sparite.', 'none', 10, true, true),
  (24, 'THE WRONG ANSWER', 'MIX IT UP', 'Fate a Marco una domanda semplice di cui conoscete la risposta. Qualunque cosa dica, insistete per 30 secondi che sia sbagliata.', 'text', 15, true, true),
  (25, 'THE SIDE QUEST', 'MIX IT UP', 'Trovate uno sconosciuto e avete 60 secondi per inventare insieme una missione segreta per Marco: fattibile, leggermente assurda e qualcosa che non farebbe spontaneamente.', 'text', 15, false, true),
  (26, 'THE STRANGER’S WISH', 'MIX IT UP', 'Chiedete a uno sconosciuto di lasciare un augurio a una persona che non conosce e che sta compiendo 30 anni.', 'text', 15, false, true),
  (27, 'THE SPEECH', 'CAUSE SOME CHAOS', 'Convincete almeno 3 persone a fare un brindisi spontaneo per Marco.', 'none', 10, true, true),
  (28, 'THE QUESTION', 'CAUSE SOME CHAOS', 'Fate a Marco una domanda completamente assurda e ottenete una risposta seria.', 'text', 15, true, true),
  (29, 'THE POSE', 'CAUSE SOME CHAOS', 'Convincete almeno 5 persone a mettersi nella stessa posa senza spiegare perché.', 'photo', 15, false, true),
  (30, 'THE CONFUSION', 'CAUSE SOME CHAOS', 'Fate qualcosa che porti Marco a dire spontaneamente: “Ma perché?”', 'text', 15, true, true),
  (31, 'THE FAKE TRADITION', 'CAUSE SOME CHAOS', 'Inventate una nuova tradizione per il compleanno di Marco e convincete almeno 3 persone a seguirla.', 'none', 10, true, true),
  (32, 'THE WRONG TOAST', 'CAUSE SOME CHAOS', 'Fate un brindisi solenne per qualcosa che non ha nulla a che vedere con il compleanno. Alla fine brindate comunque a Marco.', 'photo_optional', 10, true, true),
  (33, 'THE PAPARAZZI TEAM', 'CAUSE SOME CHAOS', 'Reclutate altre due persone e scattate 3 foto di Marco come se fosse una celebrità inseguita dai paparazzi. Caricate la migliore.', 'photo', 15, true, true),
  (34, 'THE NPC', 'CAUSE SOME CHAOS', 'Per 30 secondi rispondete a qualsiasi domanda di Marco con la stessa frase completamente scollegata. Poi tornate normali.', 'none', 10, true, true),
  (35, 'THE DEAL', 'CAUSE SOME CHAOS', 'Date a Marco due opzioni assurde e obbligatelo a sceglierne una senza spiegargli il motivo.', 'text', 15, true, true),
  (36, 'THE HYPE MAN', 'CAUSE SOME CHAOS', 'Per un minuto, ogni volta che qualcuno nomina Marco reagite come se avesse appena vinto qualcosa di enorme.', 'none', 10, true, true),
  (37, 'THE 30-YEAR-OLD', 'CAUSE SOME CHAOS', 'Chiedete a 3 persone di descrivere Marco con una sola parola. Le tre parole devono essere diverse.', 'text', 15, false, true),
  (38, 'THE PROPHECY', 'CAUSE SOME CHAOS', 'Fate predire a qualcuno che conosce appena Marco un evento stranamente specifico che gli accadrà entro 12 mesi.', 'text', 15, false, true),
  (39, 'THE QUEST', 'CAUSE SOME CHAOS', 'Fate inventare a uno sconosciuto una missione che Marco dovrebbe completare prima di compiere 31 anni.', 'text', 15, false, true),
  (40, 'THE FALSE MEMORY', 'CAUSE SOME CHAOS', 'Con uno sconosciuto inventate un falso ricordo condiviso e raccontatelo a Marco nel modo più convincente possibile.', 'text', 15, true, true),
  (41, '30 SECONDS', 'FOR MARCO', 'Registrate un video di massimo 30 secondi con un messaggio o un pensiero per Marco.', 'video', 20, false, true),
  (42, 'THE PREDICTION', 'FOR MARCO', 'Completate la frase: “A 40 anni, Marco…”', 'text', 15, false, true),
  (43, 'ONE MEMORY', 'FOR MARCO', 'Scrivete in poche righe il vostro ricordo preferito con Marco.', 'text', 15, false, true),
  (44, 'THE ADVICE', 'FOR MARCO', 'Scrivete un consiglio per i 30 anni di Marco. Non potete usare la frase “goditi la vita”.', 'text', 15, false, true),
  (45, 'THE COMPLIMENT', 'FOR MARCO', 'Scrivete qualcosa che apprezzate sinceramente di Marco senza usare le parole “simpatico”, “bravo” o “unico”.', 'text', 15, false, true),
  (46, 'THE SECRET STORY', 'FOR MARCO', 'Trovate qualcuno che conosce Marco da almeno 10 anni e fatevi raccontare una storia che Marco probabilmente non ha mai sentito raccontare così.', 'text', 15, false, true),
  (47, 'IF MARCO WERE...', 'FOR MARCO', 'Completate: “Se Marco fosse ___, sarebbe ___ perché ___.”', 'text', 15, false, true),
  (48, 'THE TRAVELER ✈️', 'FOR MARCO', 'Se domani poteste mandare Marco in viaggio senza preavviso, dove lo mandereste e perché? Massimo 2 righe.', 'text', 15, false, true),
  (49, 'READ THIS AT 40', 'FOR MARCO', 'Scrivete un messaggio che Marco dovrebbe rileggere a 40 anni. Non può essere un augurio per il suo quarantesimo compleanno.', 'text', 15, false, true),
  (50, 'FOR THE BIRTHDAY BOY ❤️', 'FOR MARCO', 'Completate la frase: “Marco, una cosa che vorrei che sapessi a 30 anni è…”', 'text', 15, false, true),
  (51, 'THE SPEECH 🎤', 'CAUSE SOME CHAOS', 'Convincete Marco a fare un mini discorso in cui ringrazia con assoluta serietà “tutta la sagra” per essere venuta apposta per il suo trentesimo.', 'photo_optional', 20, true, true),
  (52, 'THE DANCE FLOOR 🕺', 'CAUSE SOME CHAOS', 'Convincete almeno una persona che Marco non conosce a ballare con lui per qualche secondo.', 'photo', 20, true, true),
  (53, 'THE CHAMPION 🏆', 'CAUSE SOME CHAOS', 'Marco ha appena vinto qualcosa di enorme. Festeggiatelo come un campione con un’esultanza totalmente sproporzionata.', 'photo', 15, true, true),
  (54, 'THE DIRECTOR 🎬', 'CAUSE SOME CHAOS', 'Fate dirigere a qualcuno che conosce poco Marco una scena drammatica con Marco protagonista, senza spiegargli il contesto.', 'photo', 15, true, true),
  (55, 'SAME ENERGY ⚡', 'TAKE THE SHOT', 'Trovate alla festa la persona che secondo voi ha la stessa energia di Marco e scattate una foto insieme.', 'photo', 15, true, true),
  (56, 'BREAKING NEWS 🎤', 'CAUSE SOME CHAOS', 'Trasformate un evento totalmente insignificante della serata in una notizia dell’ultimo minuto con Marco coinvolto. Video massimo 10 secondi.', 'video', 20, true, true),
  (57, 'THE MUSEUM 🖼️', 'TAKE THE SHOT', 'Trasformate Marco in un’opera d’arte: scegliete una posa, inventate il titolo dell’opera e scattate una foto.', 'photo', 15, true, true),
  (58, 'THE BEFORE & AFTER', 'TAKE THE SHOT', 'Create due versioni fotografiche: “Marco a 20 anni” e “Marco a 30 anni”.', 'photo', 20, true, true),
  (59, 'THE BIRTHDAY REVIEW ⭐', 'FOR MARCO', 'Recensite Marco come se fosse un prodotto: da 1 a 5 stelle, un pregio e un difetto.', 'text', 15, false, true),
  (60, 'ONE SECOND FROM TONIGHT ❤️', 'FOR MARCO', 'Scattate una foto di un momento della serata che secondo voi Marco dovrebbe conservare. Marco non deve necessariamente esserci.', 'photo', 20, false, true)
on conflict (id) do update set
  title          = excluded.title,
  category       = excluded.category,
  text           = excluded.text,
  proof_type     = excluded.proof_type,
  points         = excluded.points,
  requires_marco = excluded.requires_marco,
  active         = excluded.active;

-- missioni tolte dal file: disattivate, non cancellate
update public.missions set active = false where id <> all (array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]);
